metric_names = ["impressions",
                "clicks",
                "clickRate",
                "activeViewViewableImpressions",
                "activeViewMeasurableImpressions",
                "activeViewEligibleImpressions",
                "totalConversions",
                "beginToRenderEligibleImpressions",
                "beginToRenderImpressions",
                "bookedActivities",
                "bookedImpressions",
                "bookedClicks",
                "bookedViewableImpressions",
                "dv360Cost",
                "dv360CostUsd",
                "downloadedImpressions",
                "richMediaHtml5Impressions",
                "roadblockImpressions",
                "trackedAds",
                "activeViewPercentageMeasurableImpressions",
                "activeViewPercentageViewableImpressions",
                "activeViewAverageViewableTimeSecond",
                "activeViewImpressionDistributionNotMeasurable",
                "activeViewImpressionDistributionNotViewable",
                "activeViewImpressionDistributionViewable",
                "activeViewNotMeasurableImpressions",
                "activeViewNotViewableImpressions",
                "activeViewPercentVisible10Seconds",
                "activeViewPercentVisibleAtStart",
                "activeViewImpressionsVisible10Seconds",
                "activeViewPercentVisibleAtFirstQuartile",
                "activeViewPercentVisibleAtMidpoint",
                "activeViewPercentVisibleAtThirdQuartile",
                "activeViewPercentVisibleAtCompletion",
                "activeViewPercentAudibleAndVisibleAtFirstQuartile",
                "activeViewPercentAudibleAndVisibleAtStart",
                "activeViewPercentAudibleAndVisibleAtMidpoint",
                "activeViewPercentAudibleAndVisibleAtThirdQuartile",
                "activeViewPercentAudibleAndVisibleAtCompletion",
                "activeViewImpressionsAudibleAndVisibleAtCompletion",
                "activeViewPercentImpressionsVisibleAtFirstQuartile",
                "activeViewPercentImpressionsVisibleAtThirdQuartile",
                "activeViewPercentImpressionsVisibleAtMidpoint",
                "activeViewPercentImpressionsVisibleAtCompletion",
                "activeViewPercentImpressionsAudibleAndVisibleAtFirstQuartile",
                "activeViewPercentImpressionsAudibleAndVisibleAtMidpoint",
                "activeViewPercentImpressionsAudibleAndVisibleAtThirdQuartile",
                "activeViewPercentImpressionsAudibleAndVisibleAtCompletion",
                "activeViewPercentAudibleImpressions",
                "activeViewPercentImpressionsAudibleAndFullyOnscreen",
                "activeViewGroupmViewableImpressions",
                "activeViewGroupmMeasurableImpressions",
                "activeViewPercentImpressionsAudibleAndFullyOnscreenForHalfDuration",
                "activeViewGroupmTrvViewableImpressions",
                "activeViewGroupmTrvMeasurableImpressions",
                "actiewViewPercentAdPlayed",
                "activeViewPercentPlayTimeVisible",
                "activeViewPercentPlayTimeAudible",
                "activeViewPercentPlayTimeAudibleAndVisible",
                "activeViewPercentFullscreen",
                "activeViewPercentBackground",
                "activeViewCustomMetricViewableRate",
                "activeViewCustomMetricViewableImpressions",
                "activeViewCustomMetricMeasurableImpressions",
                "activityClickThroughConversions",
                "activityClickThroughRevenue",
                "revenuePerClick",
                "revenuePerThousandImpressions",
                "totalConversionsRevenue",
                "activityViewThroughConversions",
                "activityViewThroughRevenue",
                "videoCompanionClicks",
                "videoCompanionImpressions",
                "richMediaTrueViewViews",
                "richMediaVideoProgressEvents",
                "richMediaVideoSkips",
                "activityDeliveryStatus",
                "clickDeliveryStatus",
                "mediaCost",
                "plannedMediaCost",
                "richMediaAverageDisplayTime",
                "richMediaAverageExpansionTime",
                "richMediaAverageInteractionTime",
                "richMediaCustomAverageTime",
                "richMediaBackupImages",
                "richMediaCustomCounters",
                "richMediaCodeServes",
                "richMediaEventCounters",
                "richMediaEventTimers",
                "richMediaCustomExits",
                "richMediaExpansionTime",
                "richMediaExpansions",
                "richMediaAverageFullScreenViewTime",
                "richMediaFullScreenImpressions",
                "richMediaFullScreenVideoCompletes",
                "richMediaFullScreenVideoPlays",
                "richMediaInteractionRate",
                "richMediaInteractiveImpressions",
                "richMediaManualCloses",
                "richMediaClickRate",
                "richMediaClicks",
                "richMediaEngagements",
                "richMediaImpressions",
                "richMediaScrolls",
                "richMediaCustomTimers",
                "richMediaDisplayTime",
                "richMediaInteractionTime",
                "richMediaInteractions",
                "richMediaAverageVideoViewTime",
                "richMediaVideoFirstQuartileCompletes",
                "richMediaVideoThirdQuartileCompletes",
                "richMediaVideoMidpoints",
                "richMediaVideoCompletions",
                "richMediaVideoCompanionClicks",
                "richMediaVideoInteractionRate",
                "richMediaVideoFullScreens",
                "richMediaVideoInteractions",
                "richMediaVideoMutes",
                "richMediaVideoPauses",
                "richMediaVideoPlays",
                "richMediaVideoReplays",
                "richMediaVideoStops",
                "richMediaVideoUnmutes",
                "richMediaVideoViewRate",
                "socialFollows",
                "socialLikes",
                "socialOtherInteractions",
                "socialSharesExternal",
                "socialReplies",
                "socialSharesInternal",
                "socialEngagementRate",
                "socialTotalEngagements"]

dimensions = [{"name":  "campaign"},
              {"name":  "campaignId"},
              {"name":  "site"},
              {"name":  "placement"},
              {"name":  "date"},
              {"name":  "activity"},
              {"name":  "activityGroup"},
              {"name":  "activityGroupId"},
              {"name":  "activityId"},
              {"name":  "ad"},
              {"name":  "adId"},
              {"name":  "adStatus"},
              {"name":  "adType"},
              {"name":  "advertiser"},
              {"name":  "advertiserGroup"},
              {"name":  "advertiserId"},
              {"name":  "asset"},
              {"name":  "assetCategory"},
              {"name":  "assetId"},
              {"name":  "assetOrientation"},
              {"name":  "contentCategory"},
              {"name":  "clickThroughUrl"},
              {"name":  "creative"},
              {"name":  "creativeId"},
              {"name":  "creativeSize"},
              {"name":  "creativeType"},
              {"name":  "creativeVersion"},
              {"name":  "floodlightConfigId"},
              {"name":  "packageRoadblockId"},
              {"name":  "packageRoadblock"},
              {"name":  "paymentSource"},
              {"name":  "placementId"},
              {"name":  "siteId"},
              {"name":  "platformType"},
              {"name":  "browserPlatform"},
              {"name":  "connectionType"},
              {"name":  "dynamicProfile"},
              {"name":  "dynamicProfileId"}
              ]
