metric_names = ["dfa:impressions",
                "dfa:clicks",
                "dfa:clickRate",
                "dfa:activeViewViewableImpressions",
                "dfa:activeViewMeasurableImpressions",
                "dfa:activeViewEligibleImpressions",
                "dfa:totalConversions",
                "dfa:beginToRenderEligibleImpressions",
                "dfa:beginToRenderImpressions",
                "dfa:bookedActivities",
                "dfa:bookedImpressions",
                "dfa:bookedClicks",
                "dfa:bookedViewableImpressions",
                "dfa:dbmCost",
                "dfa:dbmCostUsd",
                "dfa:downloadedImpressions",
                "dfa:richMediaHtml5Impressions",
                "dfa:roadblockImpressions",
                "dfa:trackedAds",
                "dfa:activeViewPercentageMeasurableImpressions",
                "dfa:activeViewPercentageViewableImpressions",
                "dfa:activeViewAverageViewableTimeSecond",
                "dfa:activeViewImpressionDistributionNotMeasurable",
                "dfa:activeViewImpressionDistributionNotViewable",
                "dfa:activeViewImpressionDistributionViewable",
                "dfa:activeViewNotMeasurableImpressions",
                "dfa:activeViewNotViewableImpressions",
                "dfa:activeViewPercentVisible10Seconds",
                "dfa:activeViewPercentVisibleAtStart",
                "dfa:activeViewImpressionsVisible10Seconds",
                "dfa:activeViewPercentVisibleAtFirstQuartile",
                "dfa:activeViewPercentVisibleAtMidpoint",
                "dfa:activeViewPercentVisibleAtThirdQuartile",
                "dfa:activeViewPercentVisibleAtCompletion",
                "dfa:activeViewPercentAudibleAndVisibleAtFirstQuartile",
                "dfa:activeViewPercentAudibleAndVisibleAtStart",
                "dfa:activeViewPercentAudibleAndVisibleAtMidpoint",
                "dfa:activeViewPercentAudibleAndVisibleAtThirdQuartile",
                "dfa:activeViewPercentAudibleAndVisibleAtCompletion",
                "dfa:activeViewImpressionsAudibleAndVisibleAtCompletion",
                "dfa:activeViewPercentImpressionsVisibleAtFirstQuartile",
                "dfa:activeViewPercentImpressionsVisibleAtThirdQuartile",
                "dfa:activeViewPercentImpressionsVisibleAtMidpoint",
                "dfa:activeViewPercentImpressionsVisibleAtCompletion",
                "dfa:activeViewPercentImpressionsAudibleAndVisibleAtFirstQuartile",
                "dfa:activeViewPercentImpressionsAudibleAndVisibleAtMidpoint",
                "dfa:activeViewPercentImpressionsAudibleAndVisibleAtThirdQuartile",
                "dfa:activeViewPercentImpressionsAudibleAndVisibleAtCompletion",
                "dfa:activeViewPercentAudibleImpressions",
                "dfa:activeViewPercentImpressionsAudibleAndFullyOnscreen",
                "dfa:activeViewGroupmViewableImpressions",
                "dfa:activeViewGroupmMeasurableImpressions",
                "dfa:activeViewPercentImpressionsAudibleAndFullyOnscreenForHalfDuration",
                "dfa:activeViewGroupmTrvViewableImpressions",
                "dfa:activeViewGroupmTrvMeasurableImpressions",
                "dfa:actiewViewPercentAdPlayed",
                "dfa:activeViewPercentPlayTimeVisible",
                "dfa:activeViewPercentPlayTimeAudible",
                "dfa:activeViewPercentPlayTimeAudibleAndVisible",
                "dfa:activeViewPercentFullscreen",
                "dfa:activeViewPercentBackground",
                "dfa:activeViewCustomMetricViewableRate",
                "dfa:activeViewCustomMetricViewableImpressions",
                "dfa:activeViewCustomMetricMeasurableImpressions",
                "dfa:activityClickThroughConversions",
                "dfa:activityClickThroughRevenue",
                "dfa:revenuePerClick",
                "dfa:revenuePerThousandImpressions",
                "dfa:totalConversionsRevenue",
                "dfa:activityViewThroughConversions",
                "dfa:activityViewThroughRevenue",
                "dfa:videoCompanionClicks",
                "dfa:videoCompanionImpressions",
                "dfa:richMediaTrueViewViews",
                "dfa:richMediaVideoProgressEvents",
                "dfa:richMediaVideoSkips",
                "dfa:activityDeliveryStatus",
                "dfa:clickDeliveryStatus",
                "dfa:mediaCost",
                "dfa:plannedMediaCost",
                "dfa:richMediaAverageDisplayTime",
                "dfa:richMediaAverageExpansionTime",
                "dfa:richMediaAverageInteractionTime",
                "dfa:richMediaCustomAverageTime",
                "dfa:richMediaBackupImages",
                "dfa:richMediaCustomCounters",
                "dfa:richMediaCodeServes",
                "dfa:richMediaEventCounters",
                "dfa:richMediaEventTimers",
                "dfa:richMediaCustomExits",
                "dfa:richMediaExpansionTime",
                "dfa:richMediaExpansions",
                "dfa:richMediaAverageFullScreenViewTime",
                "dfa:richMediaFullScreenImpressions",
                "dfa:richMediaFullScreenVideoCompletes",
                "dfa:richMediaFullScreenVideoPlays",
                "dfa:richMediaInteractionRate",
                "dfa:richMediaInteractiveImpressions",
                "dfa:richMediaManualCloses",
                "dfa:richMediaClickRate",
                "dfa:richMediaClicks",
                "dfa:richMediaEngagements",
                "dfa:richMediaImpressions",
                "dfa:richMediaScrolls",
                "dfa:richMediaCustomTimers",
                "dfa:richMediaDisplayTime",
                "dfa:richMediaInteractionTime",
                "dfa:richMediaInteractions",
                "dfa:richMediaAverageVideoViewTime",
                "dfa:richMediaVideoFirstQuartileCompletes",
                "dfa:richMediaVideoThirdQuartileCompletes",
                "dfa:richMediaVideoMidpoints",
                "dfa:richMediaVideoCompletions",
                "dfa:richMediaVideoCompanionClicks",
                "dfa:richMediaVideoInteractionRate",
                "dfa:richMediaVideoFullScreens",
                "dfa:richMediaVideoInteractions",
                "dfa:richMediaVideoMutes",
                "dfa:richMediaVideoPauses",
                "dfa:richMediaVideoPlays",
                "dfa:richMediaVideoReplays",
                "dfa:richMediaVideoStops",
                "dfa:richMediaVideoUnmutes",
                "dfa:richMediaVideoViewRate",
                "dfa:socialFollows",
                "dfa:socialLikes",
                "dfa:socialOtherInteractions",
                "dfa:socialSharesExternal",
                "dfa:socialReplies",
                "dfa:socialSharesInternal",
                "dfa:socialEngagementRate",
                "dfa:socialTotalEngagements"]

dimensions = [{"name":  "dfa:campaign"},
              {"name":  "dfa:campaignId"},
              {"name":  "dfa:site"},
              {"name":  "dfa:placement"},
              {"name":  "dfa:date"},
              {"name":  "dfa:activity"},
              {"name":  "dfa:activityGroup"},
              {"name":  "dfa:activityGroupId"},
              {"name":  "dfa:activityId"},
              {"name":  "dfa:ad"},
              {"name":  "dfa:adId"},
              {"name":  "dfa:adStatus"},
              {"name":  "dfa:adType"},
              {"name":  "dfa:advertiser"},
              {"name":  "dfa:advertiserGroup"},
              {"name":  "dfa:advertiserId"},
              {"name":  "dfa:asset"},
              {"name":  "dfa:assetCategory"},
              {"name":  "dfa:assetId"},
              {"name":  "dfa:assetOrientation"},
              {"name":  "dfa:contentCategory"},
              {"name":  "dfa:clickThroughUrl"},
              {"name":  "dfa:creative"},
              {"name":  "dfa:creativeId"},
              {"name":  "dfa:creativeSize"},
              {"name":  "dfa:creativeType"},
              {"name":  "dfa:creativeVersion"},
              {"name":  "dfa:floodlightConfigId"},
              {"name":  "dfa:packageRoadblockId"},
              {"name":  "dfa:packageRoadblock"},
              {"name":  "dfa:paymentSource"},
              {"name":  "dfa:placementId"},
              {"name":  "dfa:siteId"},
              {"name":  "dfa:platformType"},
              {"name":  "dfa:browserPlatform"},
              {"name":  "dfa:connectionType"},
              {"name":  "dfa:dynamicProfile"},
              {"name":  "dfa:dynamicProfileId"}
              ]
